version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: todo_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: todo_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - todo_network
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/todo_db
    command: >
      bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build: ./frontend
    container_name: todo_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - todo_network
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    stdin_open: true

networks:
  todo_network:
    driver: bridge

volumes:
  postgres_data: 